name: second_evaluation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  pointycastle: ^3.9.1
  image_picker: ^1.1.2
  image: ^4.4.0
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
